num_bullets = 0;//number of bullets fired at once
bullet_behavior_script = noone;//behavior for bullets
bullet_sprite_index = spr_bullet;//image for bullet
angle = 270;//angle that bullet is shot at
angle_change = 0;//change in angle from which bullet is shot over time
angle_range = 0;//angular range in which bullets are fired
fire_rate = 0;//rate at which bullets are shot
wiggle = 0;//changes the direction of the bullet every step
wiggle_interval = 0;//time it takes to jump from extreme to extreme
bullet_speed = 0;
timer = 0;
target = noone;